export const productDetails = [
  {
    id: 1,
    name: "Amazon Basics 4 Pack CR2032 3 Volt Lithium Coin Cell Battery",
    by: "by Amazon Basics",
    starcount: "59,531",
    price: "",
    shipping: "",
    available: "Currently unavailable.",
    src: "/assets/cell-battery.jpg",
  },
  {
    id: 2,
    name: "Arae Screen Protector for iPhone 12 Pro Max, HD Tempered Glass Anti Scratch Work with Most Case, 6.7 inch, 3 Pack",
    by: "by Arae",
    starcount: "321",
    price: "$6.99",
    shipping: " + $17.27 shipping",
    available: "Arrives: Thursday, May 20",
    src: "/assets/screen-protector.jpg",
  },
  {
    id: 3,
    name: "SENZER SG500 Surround Sound Pro Gaming Headset with Noise Cancelling Microphone - Detachable Memory Foam Ear Pads - Portable Foldable",
    by: "by SENZER",
    starcount: "1,613",
    price: "$23.99 ",
    shipping: " + $23.39 shipping",
    available: "Arrives: Thursday, May 20",
    src: "/assets/headset.jpg",
  },
];
